# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNAuryc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNAuryc
  pod 'React'
  pod 'AurycSDK'   

  #  pod 'RNAuryc', :path => '/Users/alcides.zelaya/Documents/Auryc/react-native-auryc/ios'
end
